name: deploy-book

# From https://jupyterbook.org/publish/gh-pages.html#automatically-host-your-book-with-github-actions
on:
  push:
    branches:
    - main

jobs:
  deploy-book:
    runs-on: ubuntu-latest
    permissions:
        contents: write
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.13

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Build the book
      run: jupyter-book build .

    - name: Publish website
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: _build/html
